# Generated by Django 4.2.8 on 2025-03-31 00:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BxGyCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repetition_limit', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('cart-wise', 'Cart-wise Coupon'), ('product-wise', 'Product-wise Coupon'), ('bxgy', 'Buy X Get Y Coupon')], max_length=20)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductWiseCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=10)),
                ('product_id', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coupon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_wise_details', to='coupons.coupon')),
            ],
        ),
        migrations.CreateModel(
            name='CartWiseCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount'), ('shipping', 'Free Shipping')], default='percentage', max_length=10)),
                ('threshold', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coupon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart_wise_details', to='coupons.coupon')),
            ],
        ),
        migrations.CreateModel(
            name='BxGyCouponGetProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('bxgy_coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_products', to='coupons.bxgycoupon')),
            ],
        ),
        migrations.CreateModel(
            name='BxGyCouponBuyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('bxgy_coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_products', to='coupons.bxgycoupon')),
            ],
        ),
        migrations.AddField(
            model_name='bxgycoupon',
            name='coupon',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bxgy_details', to='coupons.coupon'),
        ),
    ]
